#!/usr/bin/env python3
# Copyright (c) 2026 Yue
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Validate and summarize a unified end-effector tool description."""

import argparse

from franka_bringup.tool_model import ToolModelError, load_tool_description


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("tool_config", help="Path to tool.yaml")
    args = parser.parse_args()
    try:
        tool = load_tool_description(args.tool_config)
    except ToolModelError as error:
        parser.error(str(error))
    print(f"name: {tool.name}")
    print(f"mass: {tool.mass:.9g} kg")
    print(f"flange_com: {list(tool.com_parent)} m")
    print(f"tcp_offset: {list(tool.tcp['xyz'])} m")
    print(f"safety_center_from_tcp: {list(tool.collision_center_from_tcp)} m")
    print(f"safety_radius: {tool.safety_radius:.9g} m")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
